# Generated by Django 4.2.3 on 2023-11-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_actualite_image_alter_actualite_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilActualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.TextField()),
                ('post', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='media')),
                ('description', models.TextField(max_length=415)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
