# Generated by Django 4.2.3 on 2023-11-28 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_profilactualite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilactualite',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.actualite'),
        ),
    ]
