# Generated by Django 4.2.3 on 2023-11-28 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_profilactualite_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='lien',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actualite',
            name='description',
            field=models.TextField(max_length=20000),
        ),
    ]
